// Generated by Wrangler on Fri May 24 2024 17:14:22 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	USER_SALT: string;
	USER_HASH: string;
	JWT_SECRET: string;
	DB: D1Database;
}
